services:
  db:
    image: postgres:latest
    container_name: task_management_db
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  app:
#    image: openjdk:17-jdk-slim
#    container_name: spring_boot_app
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_management
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    ports:
#      - "8081:8081"
#    volumes:
#      - .:/app
#    working_dir: /app
#    command: ./gradlew bootRun
#    depends_on:
#      - db

volumes:
  postgres_data: